env: "local"  #local, dev, prod
storage_path: "./storage/storage.db"
http_server:
    address: "localhost:8080"
    timeout: 4s #время на чтение запроса и на отправку ответа
    idle_timeout: 60s #время соединения с клиентом